PORT: 9092
#DB_URL: jdbc:mysql://localhost:3306/sheps_library?createDatabaseIfNotExist=true
DB_HOST: localhost
DB_PORT: 3306
DB_NAME: sheps_library
DB_USERNAME: root
DB_PASSWORD: 328436

ADMIN_EMAIL: admin@shepherdlibrary.com
ADMIN_PASSWORD: Admin123$

MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: osodavid001@gmail.com
MAIL_PASSWORD: zsgmnshlpvwkgdsj
MAIL_FROM_EMAIL: shepsapp@product.net
MAIL_FROM_NAME: Sheps App

ZEROBOUNCE_API_KEY: 89d5d29e3f704d3a9acb4a0880045407
ZEROBOUNCE_URL: https://api.zerobounce.net/v2/validate
HAVE_I_BEEN_PAWNED_URL: https://api.pwnedpasswords.com/range

RESET_PASSWORD_EXPIRATION: 1800L
EMAIL_CONFIRMATION_EXPIRATION: 1800L
LIBRARIAN_INVITATION_EXPIRATION: 604800L

JWT_SECRET_KEY: eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTczNTE0MzQ4OCwiaWF0IjoxNzM1MTQzNDg4fQ0X0F3cS7Sqv4MsQUAvyhqAuxdd2Kiv06c2w4c5NK2z9AUPRhemJ8k3zKGXTYmhJeazJOfwzsKFn0P9oDKg
JWT_EXPIRATION: 1800L
JWT_REFRESH_EXPIRATION: 18000L