server:
  port: ${PORT}

logging:
  level:
    org.springframework.web: DEBUG

spring:
  application:
    name: ShepsLibrary

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#DB_URL: jdbc:mysql://localhost:3306/sheps_library_test?createDatabaseIfNotExist=true
#    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: ${MAIL_FROM_EMAIL}
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
#        debug: true

admin_email: ${ADMIN_EMAIL}
admin_password: ${ADMIN_PASSWORD}


client_url: http://localhost:3000
mail_from_email: ${MAIL_FROM_EMAIL}
mail_from_name: ${MAIL_FROM_NAME}

zero_bounce_api_key: ${ZEROBOUNCE_API_KEY}
zero_bounce_url: ${ZEROBOUNCE_URL}
have_i_been_pawned_url: ${HAVE_I_BEEN_PAWNED_URL}

reset_password_expiration: ${RESET_PASSWORD_EXPIRATION}
email_confirmation_expiration: ${EMAIL_CONFIRMATION_EXPIRATION}
librarian_invite_expiration: ${LIBRARIAN_INVITATION_EXPIRATION}

jwt_secret_key: ${JWT_SECRET_KEY}
jwt_access_expiration: ${JWT_EXPIRATION}
jwt_refresh_expiration: ${JWT_REFRESH_EXPIRATION}