ACTIVE_PROFILE: local
PORT: 9092
DB_HOST: localhost
DB_PORT: 3306
DB_NAME: sheps_library
DB_USERNAME: root
DB_PASSWORD: 328436

ADMIN_EMAIL: admin@shepherdlibrary.com
ADMIN_PASSWORD: Admin123$

MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: osodavid001@gmail.com
MAIL_PASSWORD: zsgmnshlpvwkgdsj
MAIL_FROM_EMAIL: shepsapp@product.net
MAIL_FROM_NAME: Sheps App

CORE_POOL_SIZE: 4
MAX_POOL_SIZE: 16
KEEP_ALIVE_TIME: 60

HIKARI_MAXIMUM_POOL_SIZE: 10
HIKARI_CONNECTION_TIMEOUT: 3000
HIKARI_IDLE_TIMEOUT: 600000
HIKARI_MAX_LIFETIME: 1800000

CACHE_MAXIMUM_SIZE: 100
CACHE_EXPIRY: 10

ZEROBOUNCE_API_KEY: 89d5d29e3f704d3a9acb4a0880045407
ZEROBOUNCE_URL: https://api.zerobounce.net/v2/validate
HAVE_I_BEEN_PAWNED_URL: https://api.pwnedpasswords.com/range

RESET_PASSWORD_EXPIRATION: 1800
EMAIL_CONFIRMATION_EXPIRATION: 1800
LIBRARIAN_INVITATION_EXPIRATION: 604800

JWT_SECRET_KEY: eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTczNTE0MzQ4OCwiaWF0IjoxNzM1MTQzNDg4fQ0X0F3cS7Sqv4MsQUAvyhqAuxdd2Kiv06c2w4c5NK2z9AUPRhemJ8k3zKGXTYmhJeazJOfwzsKFn0P9oDKg
JWT_EXPIRATION: 1800
JWT_REFRESH_EXPIRATION: 18000